#!/bin/bash

# ชื่อไฟล์รายงาน
OUTPUT="project-structure-report.md"

# ฟังก์ชันช่วยจัดรูปแบบ
function print_tree {
  local dir=$1
  local prefix=$2
  local max_depth=3

  # ใช้ find แสดงไฟล์และโฟลเดอร์ลึก 3 ชั้น
  find "$dir" -maxdepth $max_depth | sed -e "s|^$dir||" | sed 's|[^/]*/|  |g' | grep -v '^$' 
}

echo "# Project Directory Structure Report" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Generated on $(date)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## Directory Tree (up to 3 levels deep)" >> "$OUTPUT"
echo '```' >> "$OUTPUT"

# กำหนด path โฟลเดอร์โปรเจค (แก้ถ้าต้องการ)
PROJECT_ROOT="."

# สั่งพิมพ์โครงสร้างโฟลเดอร์ ลึก 3 ชั้น พร้อมจัด format
tree -L 3 "$PROJECT_ROOT" >> "$OUTPUT" 2>/dev/null || print_tree "$PROJECT_ROOT" "" >> "$OUTPUT"

echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "## Summary" >> "$OUTPUT"
echo "- Total directories: $(find "$PROJECT_ROOT" -type d | wc -l)" >> "$OUTPUT"
echo "- Total files: $(find "$PROJECT_ROOT" -type f | wc -l)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "## Top-level files:" >> "$OUTPUT"
find "$PROJECT_ROOT" -maxdepth 1 -type f -exec basename {} \; | sort >> "$OUTPUT"

echo "" >> "$OUTPUT"
echo "## Top-level directories:" >> "$OUTPUT"
find "$PROJECT_ROOT" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort >> "$OUTPUT"

echo "" >> "$OUTPUT"
echo "## Note" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "นี่คือรายละเอียดเว็บไซต์ของเรา  กำหนดให้ AI CHAT GPT เป็นนักออกแบบเว็บไซต์ และเขียน Code ระดับ Professional ตอบสนองดีทั้งบนมือถือและเดสทอปรายละเอียดเนื้อหา

โค้ดทั้งหมดทำงานภายใต้แนวทาง Dev to Dev แบบเข้มงวด ตรวจสอบโครงสร้างโปรเจกต์ให้เป็นระบบ หลีกเลี่ยงการแตกไฟล์นอกคำสั่งหรือ generate แนะนำในสิ่งที่จำเป็นและดีที่สุด

Website One Page บริการออกแบบจัดทำเว็บไซต์

แนะนำตัว Dev Baan Baan

 สวัสดีครับอย่างแรกทางผมขอแนะนำตัวก่อนว่า ผมชื่อ เอ็ม เดฟบ้าน ๆ  ฟรีแลนซ์ธรรมดาแต่ผลงานไม่ธรรมดาแน่นอน ยินดีจัดทำเว็บไซต์ทุกระดับ ตั้งแต่ ธุระกิจรัานค้าทั่วไปหรือธุระกิจเล็ก  ๆ ร้านค้าที่ไม่รู้จะเริ่มต้นอย่างไร เกิดคำถามว่าทำเว็บไซต์กับธุรกิจของเราขนาดนี้มันคุ้มใหม อย่างแรกเราปฏิเสธไม่ได้เลยว่าสังคมทุกวันนี้ ภาพลักษณ์ คือสิ่งสำคัญ ธุรกิจที่ดีภาพลักษณ์ที่ดี ย่อมเป็นตัวเลือกแรกเสมอ ยินดีให้คำปรึกษาจัดทำ ธุรกิจทุกประเภท ทุกสาขา dependencies:                                         @headlessui/react 2.2.7                               @heroicons/react 2.2.0                                @tailwindcss/aspect-ratio 0.4.2                       clsx 2.1.1                                            framer-motion 12.23.12                                html2pdf.js 0.10.3                                    lucide-react 0.537.0                                  react 18.3.1                                          react-dom 18.3.1                                      react-helmet-async 2.0.5                              react-intersection-observer 9.16.0                    react-router-dom 7.8.0                                                                                      devDependencies:                                      @eslint/js 9.32.0                                     @tailwindcss/forms 0.5.10                             @tailwindcss/postcss 4.1.11                           @tailwindcss/typography 0.5.16                        @testing-library/react 16.3.0                         @types/react 18.3.23                                  @types/react-dom 18.3.7                               @types/react-router-dom 5.3.3                         @vitejs/plugin-react 4.7.0                            autoprefixer 10.4.21                                  eslint 9.32.0                                         eslint-config-prettier 10.1.8                         eslint-plugin-prettier 5.5.4
eslint-plugin-react 7.37.5
eslint-plugin-react-hooks 5.2.0
eslint-plugin-react-refresh 0.4.20
eslint-plugin-tailwindcss 3.18.2
globals 15.15.0
jsdom 26.1.0
postcss 8.5.6
prettier 3.6.2
tailwindcss 3.4.17
typescript 5.9.2
typescript-eslint 8.39.0
vite 5.4.19
vitest 3.2.4
หลังจากนี้ จะส่งโค้ดทุกตัวในโครงสร้างที่เห็น ให้เก็บรายละเอียดส่วนต่าง ปรับให้ตอบสนองในมือถือและเดสก์ทอปเป็นมิตรกับผู้ใช้ใช้เทคนิคในการเขียนให้เกิดประโยชน์สูงสุดในแพ็คเกจที่ติดตั้งเขียนออกมาให้เข้มงวดตามมาตรฐานของโปรเจคที่ใช้ แบบ professional เมื่อส่ง config ให้ตรวจสอบตั้งค่าให้ครบถ้วนการทำงานไม่โอเคกับการที่มานั่งสอนเพราะการสอนมันสามารถหาได้ใน google เน้นการทำงานร่วมกันให้ผิดพลาดน้อยทสุดออกมาดีมากที่สุด
">> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "*This report is auto-generated by check-structure.sh*" >> "$OUTPUT"

echo "Report generated at $OUTPUT"